# Generated by Django 2.2.2 on 2019-07-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190720_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='First_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
