# Generated by Django 2.2.2 on 2019-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190720_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='First_name',
            field=models.CharField(max_length=50),
        ),
    ]
