# Generated by Django 2.2.2 on 2019-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190721_0125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='First_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Comment',
        ),
        migrations.AddField(
            model_name='contact',
            name='comment',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
