# Generated by Django 2.2.2 on 2019-07-23 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Gurdasmaan',
        ),
    ]
