# Generated by Django 2.2.2 on 2019-07-24 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactus',
            new_name='Contact',
        ),
    ]
